server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: ASAContainerDemo
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp  
 
ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true