apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asademo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: asademo
  project: default
  source:
    path: helm/demo-chart
    repoURL:  https://github.com/tcsgit/azuredemo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      