# Default values for demo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

name: asademo

image:
  repository: tcsgregistry.azurecr.io/asademo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0"
  port: 8080

service:
  type: LoadBalancer
  targetPort: 8080
  port: 80
